const SOURCE_NAME_ZH_MAP: Record<string, string> = {
  "BBC News": "英国广播公司新闻",
  "BBC World": "BBC国际新闻",
  "CNN Top": "CNN头条",
  "CNN World": "CNN国际新闻",
  "NPR News": "美国国家公共电台新闻",
  "NYTimes Home": "纽约时报首页",
  "NYTimes World": "纽约时报国际",
  "NYTimes US": "纽约时报美国",
  "NYTimes Business": "纽约时报商业",
  "NYTimes Technology": "纽约时报科技",
  "The Guardian World": "卫报国际",
  "The Guardian US": "卫报美国",
  "Al Jazeera": "半岛电视台",
  "Deutsche Welle": "德国之声",
  "Sky News World": "天空新闻国际",
  "ABC News Top": "ABC新闻头条",
  "NBC News Top": "NBC新闻头条",
  "Fox News Latest": "福克斯新闻最新",
  "NYTimes Politics": "纽约时报政治",
  "Washington Post Politics": "华盛顿邮报政治",
  "CNN US": "CNN美国",
  "DW World (EN)": "德国之声国际（英文）",
  "France24 EN": "法国24台（英文）",
  "Japan Times": "日本时报",
  "PBS NewsHour Headlines": "PBS新闻一小时头条",
  Vox: "Vox",
  "The Conversation Global Atom": "The Conversation全球",
  "WSJ World News": "华尔街日报国际新闻",
  "WSJ US Business": "华尔街日报美国商业",
  "CNBC Top News": "CNBC头条",
  "CNBC World News": "CNBC国际新闻",
  "NBC News World": "NBC国际新闻",
  "CBS News World": "CBS国际新闻",
  "ABC News World": "ABC国际新闻",
  "Korea Times": "韩国时报",
  "Channel NewsAsia": "亚洲新闻台",
  "SCMP Top News": "南华早报头条",
  "Al Jazeera English": "半岛电视台（英文）",
  "The Straits Times": "海峡时报",
  "Hong Kong Free Press": "香港自由新闻",
  "BBC Chinese": "BBC中文",
  "FT Chinese": "英国《金融时报》中文网",
};

export function toSourceNameZh(name: string): string {
  const normalized = (name || "").trim();
  if (!normalized) return name;
  return SOURCE_NAME_ZH_MAP[normalized] || normalized;
}
